spring:
  datasource:
    url: jdbc:h2:mem:accountapi
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:testdbuser}
    password: ${DB_PASSWORD:testpassword}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect